FROM caddy:2-builder AS builder
RUN xcaddy build --with github.com/caddy-dns/cloudflare

FROM caddy:2-alpine
org.opencontainers.image.source = "https://github.com/lintune/lintune-admin"
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
